#!/usr/local/bin/zsh
export PYTHONPATH=/opt/homebrew/opt/llvm/lib/python3.12/site-packages
/opt/homebrew/bin/python3 generate_rgba.py > ../lib/blend2d_rgba.rb
/opt/homebrew/bin/python3 generate_object.py > ../lib/blend2d_object.rb
/opt/homebrew/bin/python3 generate_array.py > ../lib/blend2d_array.rb
/opt/homebrew/bin/python3 generate_bitarray.py > ../lib/blend2d_bitarray.rb
/opt/homebrew/bin/python3 generate_bitset.py > ../lib/blend2d_bitset.rb
/opt/homebrew/bin/python3 generate_filesystem.py > ../lib/blend2d_filesystem.rb
/opt/homebrew/bin/python3 generate_format.py > ../lib/blend2d_format.rb
/opt/homebrew/bin/python3 generate_geometry.py > ../lib/blend2d_geometry.rb
/opt/homebrew/bin/python3 generate_string.py > ../lib/blend2d_string.rb
/opt/homebrew/bin/python3 generate_imagecodec.py > ../lib/blend2d_imagecodec.rb
/opt/homebrew/bin/python3 generate_image.py > ../lib/blend2d_image.rb
/opt/homebrew/bin/python3 generate_random.py > ../lib/blend2d_random.rb
/opt/homebrew/bin/python3 generate_fontdefs.py > ../lib/blend2d_fontdefs.rb
/opt/homebrew/bin/python3 generate_fontdata.py > ../lib/blend2d_fontdata.rb
/opt/homebrew/bin/python3 generate_glyphrun.py > ../lib/blend2d_glyphrun.rb
/opt/homebrew/bin/python3 generate_glyphrun.py > ../lib/blend2d_glyphrun.rb
/opt/homebrew/bin/python3 generate_glyphbuffer.py > ../lib/blend2d_glyphbuffer.rb
/opt/homebrew/bin/python3 generate_path.py > ../lib/blend2d_path.rb
/opt/homebrew/bin/python3 generate_fontface.py > ../lib/blend2d_fontface.rb
/opt/homebrew/bin/python3 generate_fontfeaturesettings.py > ../lib/blend2d_fontfeaturesettings.rb
/opt/homebrew/bin/python3 generate_fontvariationsettings.py > ../lib/blend2d_fontvariationsettings.rb
/opt/homebrew/bin/python3 generate_font.py > ../lib/blend2d_font.rb
/opt/homebrew/bin/python3 generate_fontmanager.py > ../lib/blend2d_fontmanager.rb
/opt/homebrew/bin/python3 generate_matrix.py > ../lib/blend2d_matrix.rb
/opt/homebrew/bin/python3 generate_gradient.py > ../lib/blend2d_gradient.rb
/opt/homebrew/bin/python3 generate_imagedecoder.py > ../lib/blend2d_imagedecoder.rb
/opt/homebrew/bin/python3 generate_imageencoder.py > ../lib/blend2d_imageencoder.rb
/opt/homebrew/bin/python3 generate_pattern.py > ../lib/blend2d_pattern.rb
/opt/homebrew/bin/python3 generate_pixelconverter.py > ../lib/blend2d_pixelconverter.rb
/opt/homebrew/bin/python3 generate_runtime.py > ../lib/blend2d_runtime.rb
/opt/homebrew/bin/python3 generate_var.py > ../lib/blend2d_var.rb
/opt/homebrew/bin/python3 generate_context.py > ../lib/blend2d_context.rb
/opt/homebrew/bin/python3 generate_api.py > ../lib/blend2d_api.rb
