# Ruby-Blend2D : Yet another Blend2D wrapper for Ruby
#
# * https://github.com/vaiorabbit/blend2d-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'
require_relative 'blend2d_fontdefs'

module Blend2D
  extend FFI::Library
  # Define/Macro


  # Enum

  BL_GLYPH_RUN_NO_FLAGS = 0
  BL_GLYPH_RUN_FLAG_UCS4_CONTENT = 268435456
  BL_GLYPH_RUN_FLAG_INVALID_TEXT = 536870912
  BL_GLYPH_RUN_FLAG_UNDEFINED_GLYPHS = 1073741824
  BL_GLYPH_RUN_FLAG_INVALID_FONT_DATA = 2147483648
  BL_GLYPH_RUN_FLAG_FORCE_UINT = 4294967295
  BL_GLYPH_PLACEMENT_TYPE_NONE = 0
  BL_GLYPH_PLACEMENT_TYPE_ADVANCE_OFFSET = 1
  BL_GLYPH_PLACEMENT_TYPE_DESIGN_UNITS = 2
  BL_GLYPH_PLACEMENT_TYPE_USER_UNITS = 3
  BL_GLYPH_PLACEMENT_TYPE_ABSOLUTE_UNITS = 4
  BL_GLYPH_PLACEMENT_TYPE_MAX_VALUE = 4
  BL_GLYPH_PLACEMENT_TYPE_FORCE_UINT = 4294967295

  # Typedef

  typedef :int, :BLGlyphRunFlags
  typedef :int, :BLGlyphPlacementType

  # Struct

  class BLGlyphRun < FFI::Struct
    layout(
      :glyphData, :pointer,
      :placementData, :pointer,
      :size, :ulong,
      :reserved, :uchar,
      :placementType, :uchar,
      :glyphAdvance, :char,
      :placementAdvance, :char,
      :flags, :uint,
    )
  end


  # Function

  def self.setup_glyphrun_symbols(output_error = false)
    symbols = [
    ]
    apis = {
    }
    args = {
    }
    retvals = {
    }
    symbols.each do |sym|
      begin
        attach_function apis[sym], sym, args[sym], retvals[sym]
      rescue FFI::NotFoundError => error
        $stderr.puts("[Warning] Failed to import #{sym} (#{error}).") if output_error
      end
    end
  end

end

