# Ruby-Blend2D : Yet another Blend2D wrapper for Ruby
#
# * https://github.com/vaiorabbit/blend2d-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'
require_relative 'blend2d_object'

module Blend2D
  extend FFI::Library
  # Define/Macro


  # Enum


  # Typedef


  # Struct

  class BLStringCore < FFI::Struct
    layout(
      :_d, BLObjectDetail,
    )
    def _d = self[:_d]
    def _d=(v) self[:_d] = v end
    def init() = blStringInit(self)
    def self.create()
      instance = BLStringCore.new
      blStringInit(instance)
      instance
    end
    def initMove(other) = blStringInitMove(self, other)
    def initWeak(other) = blStringInitWeak(self, other)
    def initWithData(str, size) = blStringInitWithData(self, str, size)
    def destroy() = blStringDestroy(self)
    def reset() = blStringReset(self)
    def getData() = blStringGetData(self)
    def getSize() = blStringGetSize(self)
    def getCapacity() = blStringGetCapacity(self)
    def clear() = blStringClear(self)
    def shrink() = blStringShrink(self)
    def reserve(n) = blStringReserve(self, n)
    def resize(n, fill) = blStringResize(self, n, fill)
    def makeMutable(dataOut) = blStringMakeMutable(self, dataOut)
    def modifyOp(op, n, dataOut) = blStringModifyOp(self, op, n, dataOut)
    def insertOp(index, n, dataOut) = blStringInsertOp(self, index, n, dataOut)
    def assignMove(other) = blStringAssignMove(self, other)
    def assignWeak(other) = blStringAssignWeak(self, other)
    def assignDeep(other) = blStringAssignDeep(self, other)
    def assignData(str, n) = blStringAssignData(self, str, n)
    def applyOpChar(op, c, n) = blStringApplyOpChar(self, op, c, n)
    def applyOpData(op, str, n) = blStringApplyOpData(self, op, str, n)
    def applyOpString(op, other) = blStringApplyOpString(self, op, other)
    def applyOpFormat(op, fmt) = blStringApplyOpFormat(self, op, fmt)
    def applyOpFormatV(op, fmt, ap) = blStringApplyOpFormatV(self, op, fmt, ap)
    def insertChar(index, c, n) = blStringInsertChar(self, index, c, n)
    def insertData(index, str, n) = blStringInsertData(self, index, str, n)
    def insertString(index, other) = blStringInsertString(self, index, other)
    def removeIndex(index) = blStringRemoveIndex(self, index)
    def removeRange(rStart, rEnd) = blStringRemoveRange(self, rStart, rEnd)
    def equals(b) = blStringEquals(a, b)
    def equalsData(str, n) = blStringEqualsData(self, str, n)
    def compare(b) = blStringCompare(a, b)
    def compareData(str, n) = blStringCompareData(self, str, n)
  end

  class BLStringImpl < FFI::Struct
    layout(
      :size, :ulong,
      :capacity, :ulong,
    )
    def size = self[:size]
    def size=(v) self[:size] = v end
    def capacity = self[:capacity]
    def capacity=(v) self[:capacity] = v end
    def self.create_as(_size_, _capacity_)
      instance = BLStringImpl.new
      instance[:size] = _size_
      instance[:capacity] = _capacity_
      instance
    end
  end


  # Function

  def self.setup_string_symbols(output_error = false)
    symbols = [
      :blStringInit,
      :blStringInitMove,
      :blStringInitWeak,
      :blStringInitWithData,
      :blStringDestroy,
      :blStringReset,
      :blStringGetData,
      :blStringGetSize,
      :blStringGetCapacity,
      :blStringClear,
      :blStringShrink,
      :blStringReserve,
      :blStringResize,
      :blStringMakeMutable,
      :blStringModifyOp,
      :blStringInsertOp,
      :blStringAssignMove,
      :blStringAssignWeak,
      :blStringAssignDeep,
      :blStringAssignData,
      :blStringApplyOpChar,
      :blStringApplyOpData,
      :blStringApplyOpString,
      :blStringApplyOpFormat,
      :blStringApplyOpFormatV,
      :blStringInsertChar,
      :blStringInsertData,
      :blStringInsertString,
      :blStringRemoveIndex,
      :blStringRemoveRange,
      :blStringEquals,
      :blStringEqualsData,
      :blStringCompare,
      :blStringCompareData,
    ]
    apis = {
      :blStringInit => :blStringInit,
      :blStringInitMove => :blStringInitMove,
      :blStringInitWeak => :blStringInitWeak,
      :blStringInitWithData => :blStringInitWithData,
      :blStringDestroy => :blStringDestroy,
      :blStringReset => :blStringReset,
      :blStringGetData => :blStringGetData,
      :blStringGetSize => :blStringGetSize,
      :blStringGetCapacity => :blStringGetCapacity,
      :blStringClear => :blStringClear,
      :blStringShrink => :blStringShrink,
      :blStringReserve => :blStringReserve,
      :blStringResize => :blStringResize,
      :blStringMakeMutable => :blStringMakeMutable,
      :blStringModifyOp => :blStringModifyOp,
      :blStringInsertOp => :blStringInsertOp,
      :blStringAssignMove => :blStringAssignMove,
      :blStringAssignWeak => :blStringAssignWeak,
      :blStringAssignDeep => :blStringAssignDeep,
      :blStringAssignData => :blStringAssignData,
      :blStringApplyOpChar => :blStringApplyOpChar,
      :blStringApplyOpData => :blStringApplyOpData,
      :blStringApplyOpString => :blStringApplyOpString,
      :blStringApplyOpFormat => :blStringApplyOpFormat,
      :blStringApplyOpFormatV => :blStringApplyOpFormatV,
      :blStringInsertChar => :blStringInsertChar,
      :blStringInsertData => :blStringInsertData,
      :blStringInsertString => :blStringInsertString,
      :blStringRemoveIndex => :blStringRemoveIndex,
      :blStringRemoveRange => :blStringRemoveRange,
      :blStringEquals => :blStringEquals,
      :blStringEqualsData => :blStringEqualsData,
      :blStringCompare => :blStringCompare,
      :blStringCompareData => :blStringCompareData,
    }
    args = {
      :blStringInit => [:pointer],
      :blStringInitMove => [:pointer, :pointer],
      :blStringInitWeak => [:pointer, :pointer],
      :blStringInitWithData => [:pointer, :pointer, :ulong],
      :blStringDestroy => [:pointer],
      :blStringReset => [:pointer],
      :blStringGetData => [:pointer],
      :blStringGetSize => [:pointer],
      :blStringGetCapacity => [:pointer],
      :blStringClear => [:pointer],
      :blStringShrink => [:pointer],
      :blStringReserve => [:pointer, :ulong],
      :blStringResize => [:pointer, :ulong, :char],
      :blStringMakeMutable => [:pointer, :pointer],
      :blStringModifyOp => [:pointer, :int, :ulong, :pointer],
      :blStringInsertOp => [:pointer, :ulong, :ulong, :pointer],
      :blStringAssignMove => [:pointer, :pointer],
      :blStringAssignWeak => [:pointer, :pointer],
      :blStringAssignDeep => [:pointer, :pointer],
      :blStringAssignData => [:pointer, :pointer, :ulong],
      :blStringApplyOpChar => [:pointer, :int, :char, :ulong],
      :blStringApplyOpData => [:pointer, :int, :pointer, :ulong],
      :blStringApplyOpString => [:pointer, :int, :pointer],
      :blStringApplyOpFormat => [:pointer, :int, :pointer],
      :blStringApplyOpFormatV => [:pointer, :int, :pointer, :int],
      :blStringInsertChar => [:pointer, :ulong, :char, :ulong],
      :blStringInsertData => [:pointer, :ulong, :pointer, :ulong],
      :blStringInsertString => [:pointer, :ulong, :pointer],
      :blStringRemoveIndex => [:pointer, :ulong],
      :blStringRemoveRange => [:pointer, :ulong, :ulong],
      :blStringEquals => [:pointer, :pointer],
      :blStringEqualsData => [:pointer, :pointer, :ulong],
      :blStringCompare => [:pointer, :pointer],
      :blStringCompareData => [:pointer, :pointer, :ulong],
    }
    retvals = {
      :blStringInit => :uint,
      :blStringInitMove => :uint,
      :blStringInitWeak => :uint,
      :blStringInitWithData => :uint,
      :blStringDestroy => :uint,
      :blStringReset => :uint,
      :blStringGetData => :pointer,
      :blStringGetSize => :ulong,
      :blStringGetCapacity => :ulong,
      :blStringClear => :uint,
      :blStringShrink => :uint,
      :blStringReserve => :uint,
      :blStringResize => :uint,
      :blStringMakeMutable => :uint,
      :blStringModifyOp => :uint,
      :blStringInsertOp => :uint,
      :blStringAssignMove => :uint,
      :blStringAssignWeak => :uint,
      :blStringAssignDeep => :uint,
      :blStringAssignData => :uint,
      :blStringApplyOpChar => :uint,
      :blStringApplyOpData => :uint,
      :blStringApplyOpString => :uint,
      :blStringApplyOpFormat => :uint,
      :blStringApplyOpFormatV => :uint,
      :blStringInsertChar => :uint,
      :blStringInsertData => :uint,
      :blStringInsertString => :uint,
      :blStringRemoveIndex => :uint,
      :blStringRemoveRange => :uint,
      :blStringEquals => :int,
      :blStringEqualsData => :int,
      :blStringCompare => :int,
      :blStringCompareData => :int,
    }
    symbols.each do |sym|
      begin
        attach_function apis[sym], sym, args[sym], retvals[sym]
      rescue FFI::NotFoundError => error
        $stderr.puts("[Warning] Failed to import #{sym} (#{error}).") if output_error
      end
    end
  end

end

