# Ruby-Blend2D : Yet another Blend2D wrapper for Ruby
#
# * https://github.com/vaiorabbit/blend2d-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'
require_relative 'blend2d_imagecodec'
require_relative 'blend2d_object'
require_relative 'blend2d_string'

module Blend2D
  extend FFI::Library
  # Define/Macro


  # Enum


  # Typedef


  # Struct

  class BLImageEncoderVirt < FFI::Struct
    layout(
      :base, BLObjectVirtBase,
      :restart, :pointer,
      :writeFrame, :pointer,
    )
  end

  class BLImageEncoderImpl < FFI::Struct
    layout(
      :virt, :pointer,
      :codec, BLImageCodecCore,
      :lastResult, :uint,
      :handle, :pointer,
      :frameIndex, :ulong_long,
      :bufferIndex, :ulong,
    )
  end

  class BLImageEncoderCore < FFI::Struct
    layout(
      :_d, BLObjectDetail,
    )
  end


  # Function

  def self.setup_imageencoder_symbols(output_error = false)
    symbols = [
      :blImageEncoderInit,
      :blImageEncoderInitMove,
      :blImageEncoderInitWeak,
      :blImageEncoderDestroy,
      :blImageEncoderReset,
      :blImageEncoderAssignMove,
      :blImageEncoderAssignWeak,
      :blImageEncoderRestart,
      :blImageEncoderWriteFrame,
    ]
    apis = {
      :blImageEncoderInit => :blImageEncoderInit,
      :blImageEncoderInitMove => :blImageEncoderInitMove,
      :blImageEncoderInitWeak => :blImageEncoderInitWeak,
      :blImageEncoderDestroy => :blImageEncoderDestroy,
      :blImageEncoderReset => :blImageEncoderReset,
      :blImageEncoderAssignMove => :blImageEncoderAssignMove,
      :blImageEncoderAssignWeak => :blImageEncoderAssignWeak,
      :blImageEncoderRestart => :blImageEncoderRestart,
      :blImageEncoderWriteFrame => :blImageEncoderWriteFrame,
    }
    args = {
      :blImageEncoderInit => [:pointer],
      :blImageEncoderInitMove => [:pointer, :pointer],
      :blImageEncoderInitWeak => [:pointer, :pointer],
      :blImageEncoderDestroy => [:pointer],
      :blImageEncoderReset => [:pointer],
      :blImageEncoderAssignMove => [:pointer, :pointer],
      :blImageEncoderAssignWeak => [:pointer, :pointer],
      :blImageEncoderRestart => [:pointer],
      :blImageEncoderWriteFrame => [:pointer, :pointer, :pointer],
    }
    retvals = {
      :blImageEncoderInit => :uint,
      :blImageEncoderInitMove => :uint,
      :blImageEncoderInitWeak => :uint,
      :blImageEncoderDestroy => :uint,
      :blImageEncoderReset => :uint,
      :blImageEncoderAssignMove => :uint,
      :blImageEncoderAssignWeak => :uint,
      :blImageEncoderRestart => :uint,
      :blImageEncoderWriteFrame => :uint,
    }
    symbols.each do |sym|
      begin
        attach_function apis[sym], sym, args[sym], retvals[sym]
      rescue FFI::NotFoundError => error
        $stderr.puts("[Warning] Failed to import #{sym} (#{error}).") if output_error
      end
    end
  end

end

