# Ruby-Blend2D : Yet another Blend2D wrapper for Ruby
#
# * https://github.com/vaiorabbit/blend2d-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'

module Blend2D
  extend FFI::Library
  # Define/Macro


  # Enum


  # Typedef


  # Struct

  class BLRgba32 < FFI::Struct
    layout(
      :value, :uint,
    )
  end

  class BLRgba64 < FFI::Struct
    layout(
      :value, :ulong_long,
    )
  end

  class BLRgba < FFI::Struct
    layout(
      :r, :float,
      :g, :float,
      :b, :float,
      :a, :float,
    )
  end


  # Function

  def self.setup_rgba_symbols(output_error = false)
    symbols = [
    ]
    apis = {
    }
    args = {
    }
    retvals = {
    }
    symbols.each do |sym|
      begin
        attach_function apis[sym], sym, args[sym], retvals[sym]
      rescue FFI::NotFoundError => error
        $stderr.puts("[Warning] Failed to import #{sym} (#{error}).") if output_error
      end
    end
  end

end

